apiVersion: apps.aloys.cn/v1
kind: Application
metadata:
  labels:
    app.kubernetes.io/name: aloys-application-operator
    app.kubernetes.io/managed-by: kustomize
  name: application-sample
spec:
  # TODO(user): Add fields here
